# the version of docker compose
version: '3.8'
# those are projects that we want images and containers for
services:
  # not necessary the same name
  api:
  # to build the image: the path to docker file
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
    # relative path to that docker compose
      - ./api:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client_c
    ports:
      - '3000:3000'
    # If we're working with windows we should add that
    stdin_open: true
    tty: true
    